# Site settings
title: The Balance Between
email: hdcasey231@gmail.com
description: A blog to create a balanced and healthy lifestyle.
baseurl: "/the-balance-between"
url: ""
twitter_username: hannahdcasey
avatar: "" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Hannah Casey" # Set default author name
      categories: "travel"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
