# Site settings
title: Hannah's Blog
email: hdcasey231@gmail.com
description: My Blog.
baseurl: "/hannah"
url: ""
twitter_username: hannahdcasey
avatar: "" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "My Author" # Set default author name
      categories: "cats"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
